export const products = [
    {  name: 'Camisa Hombre', price: 29.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Pantalones Hombre', price: 39.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Chaqueta Hombre', price: 49.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Zapatos Hombre', price: 59.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Corbata Hombre', price: 19.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Camiseta Hombre', price: 15.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Chaleco Hombre', price: 24.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Sudadera Hombre', price: 34.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Sombrero Hombre', price: 14.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Reloj Hombre', price: 89.99, category: 'man' , stock:{cant:10, isAvailable:true}},
    {  name: 'Vestido Mujer', price: 49.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Falda Mujer', price: 29.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Blusa Mujer', price: 19.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Zapatos Mujer', price: 59.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Bolso Mujer', price: 39.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Abrigo Mujer', price: 89.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Pantalones Mujer', price: 34.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Camiseta Mujer', price: 14.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Chal Mujer', price: 24.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
    {  name: 'Reloj Mujer', price: 79.99, category: 'woman' , stock:{cant:10, isAvailable:true}},
  ];